In [1]:
import nivapy3 as nivapy
import pandas as pd
import os
from tqdm import tqdm

## Extract water chemistry data from Vannmiljø
Accessing data using James's notebook vannmiljo_api.ipynb (https://nbviewer.org/github/NIVANorge/dstoolkit_cookbook/blob/master/notebooks/vannmiljo_api.ipynb).
I am extracting data for **all water bodies in Norway** using Vassdragsområder. First, a list of all Vassdragsområder is created and then the data are extracted and saved for each Vassdragsområder separately. 

**NOTES:** 
* Vassdragsområder with numbers "015", "219", "301", "302", "305", "309" cause error during extraction or provide empty files. I filter them out during the first water chemistry data extraction. To extract the data for the missing vassoms I get the water loaction codes from Vannmiljø manualy, and then extract the water chemistry data using the API and water location codes.
* Query stations extraction provides **CoordX_deg and CoordY_deg** which are the **same for all stations**. So, I am extracting only CoordX and CoordY.
* Query water chemistry stting MediumID: 'VF' (Ferskvann) and selecting columns of interest during extraction causing errors for some vassoms. So, I am not filtering at this stage but extracting all available data.

#### User inputs

In [2]:
# Vassdragsområder list
vassoms = [f"{id:03d}" for id in range(1, 248)] + [f"{id:03d}" for id in range(301, 316)] 
vassoms = [vassom for vassom in vassoms if vassom not in ["015", "219", "301", "302", "305", "309"]]

# Water location codes for missing Vassoms
path = "../data/raw_data/water_chemistry/missing_vass_info/"
wc_codes = []
for file in os.listdir(path):
    if file.endswith(".xlsx"):
        file_path = os.path.join(path, file)
        df = pd.read_excel(file_path)
        if 'Vannlokalitetskode' in df.columns:
            wc_codes.extend(list(df['Vannlokalitetskode'].unique()))

# Parameters of interest
# pars = ["TOC", "DOC", "N-TOT", "P-TOT"]

# Export date (for filenaming)
export_date = "2026-03"

# Columns of interest
cols_stn = ["WaterLocationID",
            "WaterLocationCode",
            "CoordX",
            "CoordY",
            "WaterCategory",
            "Name",
            "WaterBodyID",
            "WaterBody",
            "Elevation",
            "FeatureType",
            "Fylke",
            "Kommune",
            "Vassdragsomrade",
            "Vannomrade",
            "Vannregion"
]

In [3]:
# List parameters
# (Note: QualityElementID is useful for filtering further. Relevant:
# * ION: ions
# * PAR: particles
# * NAE: Naeringstoffer
# * FOR: Forsuring
# * FAR: Farge
# par_df = nivapy.da.get_data_from_vannmiljo("GetParameterList")
# par_df = par_df[['ParameterID', 'Name', 'Description', 'QualityElementID']]
# par_df.to_csv(r"../data/vannmiljo_par_list.csv", index=False)
# par_df.head()

In [21]:
# Read in list of params to get
param_list_fpath = r'../data/vannmiljo_getparams.csv'

# Read in. Need specific NaN handling, as "NA" (Natrium) was being read as NaN
params_df = pd.read_csv(
    param_list_fpath,
    index_col=0,
    keep_default_na=False,   # disable automatic NA detection
    na_values=[]             # ensure nothing is treated as NA unless specified
)

pars = params_df.loc[params_df['Get'] == '1'].index.to_list()
pars

['N-SNOX',
 'N-TOT',
 'P-TOT',
 'TOC',
 'SIO2',
 'N-NH4',
 'HCO3',
 'P-PO4',
 'PH',
 'CA',
 'CL',
 'DOC',
 'SI-SIO2',
 'NA',
 'N-NO3',
 'P-ORTO',
 'POC',
 'TIC',
 'P-TDP',
 'DIC']

### Query stations using Vassdragsområder

In [22]:
data = {"VassdragsomradeIDFilter": vassoms}
stn_df = nivapy.da.post_data_to_vannmiljo("GetWaterLocations", data=data)
stn_df = stn_df[cols_stn]
stn_df.to_csv(f"../data/raw_data/water_chemistry/wc_metadata_{export_date}.csv", index=False)
stn_df.head()

,WaterLocationID,WaterLocationCode,CoordX,CoordY,WaterCategory,Name,WaterBodyID,WaterBody,Elevation,FeatureType,Fylke,Kommune,Vassdragsomrade,Vannomrade,Vannregion
0,27481,01.20-27481,142615.7791,6.499630e+06,C,Skibvigen (10),0120030201-2-C,Tromøysundet,0.0,point,Agder,Arendal,Vegårsvassdraget og Gjerstadvassdraget/kyst Kr...,Nidelva,Agder
1,27482,01.20-27482,140686.0541,6.498295e+06,C,"Tromøysund 3, Trollenes",0120030201-2-C,Tromøysundet,0.0,point,Agder,Arendal,Vegårsvassdraget og Gjerstadvassdraget/kyst Kr...,Nidelva,Agder
2,27499,012-27499,255052.1685,6.702456e+06,L,Jarenvatnet,012-557-L,Jarenvatnet,200.0,point,Innlandet,Gran,Drammensvassdraget/Drammensfjorden vest,Randsfjorden,Vest-Viken
3,27564,01.01-27564,270673.4953,6.562393e+06,C,"Singlefjorden/Hvalerbassenget, Møkkalassene no...",0101010405-C,Østerelva,0.0,point,Østfold,Fredrikstad,Glommavassdraget/Hvaler og Singlefjorden,Glomma sør for Øyeren,Glomma
4,27681,012-27681,151506.3281,6.796696e+06,L,Vangsmjøse,012-517-L,Vangsmjøsi,466.0,point,Innlandet,Vang,Drammensvassdraget/Drammensfjorden vest,Valdres,Vest-Viken

### Query stations using water location codes (only for the missing Vassdragsområder)

In [23]:
data = {"WaterLocationCodeFilter": wc_codes}
stn_missing_vass_df = nivapy.da.post_data_to_vannmiljo("GetWaterLocations", data=data)
stn_missing_vass_df = stn_missing_vass_df[cols_stn]
stn_missing_vass_df.to_csv(f"../data/raw_data/water_chemistry/wc_metadata_missing_vass_{export_date}.csv", index=False)
stn_missing_vass_df.head()

,WaterLocationID,WaterLocationCode,CoordX,CoordY,WaterCategory,Name,WaterBodyID,WaterBody,Elevation,FeatureType,Fylke,Kommune,Vassdragsomrade,Vannomrade,Vannregion
0,28201,015-28201,199303.3301,6.621249e+06,R,1084 BUSEN07 Labro. Numedalslågen,015-1201-R,Numedalslågen fra Skollenborg til Labro,118.0,point,Buskerud,Kongsberg,Numedalslågen og Siljanvassdraget/kyst Sandefj...,Numedalslågen,Vest-Viken
1,28202,015-28202,196191.8539,6.632849e+06,R,Pikerfossen. Numedalslågen,015-1299-R,Numedalslågen fra Fossan til Pikerfoss,166.0,point,Buskerud,Kongsberg,Numedalslågen og Siljanvassdraget/kyst Sandefj...,Numedalslågen,Vest-Viken
2,28502,015-28502,213106.6201,6.564370e+06,R,"Delesandbekken, Tilløpsbekk Farris",015-171-R,Delesand,27.0,point,Vestfold,Larvik,Numedalslågen og Siljanvassdraget/kyst Sandefj...,Siljan - Farrisvassdraget,Vest-Viken
3,28533,015-28533,170265.3161,6.677310e+06,L,Kravikfjorden,015-18525-L,Kravikfjorden,262.0,point,Buskerud,Nore og Uvdal,Numedalslågen og Siljanvassdraget/kyst Sandefj...,Numedalslågen,Vest-Viken
4,28534,015-28534,195350.3501,6.645442e+06,R,Lampeland,015-1299-R,Numedalslågen fra Fossan til Pikerfoss,175.0,point,Buskerud,Flesberg,Numedalslågen og Siljanvassdraget/kyst Sandefj...,Numedalslågen,Vest-Viken

### Query water chemistry using Vassdragsområder

In [24]:
for vassom in tqdm(vassoms):
    all_data = []
    for par in pars:
        data = {
            "FromRegDate": "1900-01-01",
            "ParameterIDFilter": [par],
            "VassdragsomradeIDFilter": [vassom],
        }
        wc_df = nivapy.da.post_data_to_vannmiljo("GetRegistrations", data=data)
        all_data.append(wc_df)

    # concatenate once at the end
    all_data = pd.concat(all_data, ignore_index=True)
    all_data.to_csv(f'../data/raw_data/water_chemistry/{vassom}_data_export-{export_date}.csv', index=False)

  0%|          | 0/256 [00:00<?, ?it/s]/tmp/ipykernel_8174/1387564697.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_data = pd.concat(all_data, ignore_index=True)
  0%|          | 1/256 [01:12<5:06:23, 72.09s/it]/tmp/ipykernel_8174/1387564697.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_data = pd.concat(all_data, ignore_index=True)
  1%|          | 2/256 [04:30<10:20:39, 146.61s/it]/tmp/ipykernel_8174/1387564697.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_data = pd.concat(all_data, ignore_index=True)
  1%|          | 3/256 [05:45<7:59:34, 113.73s/it] /tmp/ipykernel_8174/1387564697.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_data = pd.concat(all_data, ignore_index=True)
  2%|▏         | 4/256 [06:38<6:17:09, 89.80s/it] /tmp/ipykernel_8174/1387564697.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_data = pd.concat(all_data, ignore_index=True)
  2%|▏         | 5/256 [08:03<6:08:01, 87.97s/it]/tmp/ipykernel_8174/1387564697.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_data = pd.concat(all_data, ignore_index=True)
  2%|▏         | 6/256 [09:16<5:45:32, 82.93s/it]/tmp/ipykernel_8174/1387564697.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_data = pd.concat(all_data, ignore_index=True)
  3%|▎         | 7/256 [10:17<5:15:02, 75.91s/it]/tmp/ipykernel_8174/1387564697.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_data = pd.concat(all_data, ignore_index=True)
  3%|▎         | 8/256 [11:23<5:00:11, 72.63s/it]/tmp/ipykernel_8174/1387564697.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_data = pd.concat(all_data, ignore_index=True)
  4%|▎         | 9/256 [12:31<4:53:27, 71.28s/it]/tmp/ipykernel_8174/1387564697.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_data = pd.concat(all_data, ignore_index=True)
  4%|▍         | 10/256 [13:23<4:26:47, 65.07s/it]/tmp/ipykernel_8174/1387564697.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_data = pd.concat(all_data, ignore_index=True)
  4%|▍         | 11/256 [14:25<4:21:54, 64.14s/it]/tmp/ipykernel_8174/1387564697.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_data = pd.concat(all_data, ignore_index=True)
  5%|▍         | 12/256 [16:53<6:04:36, 89.66s/it]/tmp/ipykernel_8174/1387564697.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_data = pd.concat(all_data, ignore_index=True)
  5%|▌         | 13/256 [17:49<5:22:54, 79.73s/it]/tmp/ipykernel_8174/1387564697.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_data = pd.concat(all_data, ignore_index=True)
  5%|▌         | 14/256 [18:57<5:06:28, 75.99s/it]/tmp/ipykernel_8174/1387564697.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_data = pd.concat(all_data, ignore_index=True)
  6%|▌         | 15/256 [20:15<5:08:12, 76.73s/it]/tmp/ipykernel_8174/1387564697.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_data = pd.concat(all_data, ignore_index=True)
  6%|▋         | 16/256 [21:14<4:45:49, 71.45s/it]/tmp/ipykernel_8174/1387564697.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_data = pd.concat(all_data, ignore_index=True)
  7%|▋         | 17/256 [22:23<4:40:41, 70.47s/it]/tmp/ipykernel_8174/1387564697.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_data = pd.concat(all_data, ignore_index=True)
  7%|▋         | 18/256 [23:44<4:52:30, 73.74s/it]/tmp/ipykernel_8174/1387564697.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_data = pd.concat(all_data, ignore_index=True)
  7%|▋         | 19/256 [24:56<4:49:50, 73.38s/it]/tmp/ipykernel_8174/1387564697.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_data = pd.concat(all_data, ignore_index=True)
  8%|▊         | 20/256 [26:00<4:36:28, 70.29s/it]/tmp/ipykernel_8174/1387564697.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_data = pd.concat(all_data, ignore_index=True)
  8%|▊         | 21/256 [27:04<4:28:10, 68.47s/it]/tmp/ipykernel_8174/1387564697.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_data = pd.concat(all_data, ignore_index=True)
  9%|▊         | 22/256 [27:55<4:06:41, 63.25s/it]/tmp/ipykernel_8174/1387564697.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_data = pd.concat(all_data, ignore_index=True)
  9%|▉         | 24/256 [29:42<3:44:20, 58.02s/it]/tmp/ipykernel_8174/1387564697.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_data = pd.concat(all_data, ignore_index=True)
 10%|▉         | 25/256 [30:41<3:45:15, 58.51s/it]/tmp/ipykernel_8174/1387564697.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_data = pd.concat(all_data, ignore_index=True)
 10%|█         | 26/256 [31:43<3:48:35, 59.63s/it]/tmp/ipykernel_8174/1387564697.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_data = pd.concat(all_data, ignore_index=True)
 11%|█         | 27/256 [32:49<3:53:55, 61.29s/it]/tmp/ipykernel_8174/1387564697.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_data = pd.concat(all_data, ignore_index=True)
 11%|█         | 28/256 [33:39<3:40:48, 58.11s/it]/tmp/ipykernel_8174/1387564697.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_data = pd.concat(all_data, ignore_index=True)
 11%|█▏        | 29/256 [34:33<3:34:35, 56.72s/it]/tmp/ipykernel_8174/1387564697.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_data = pd.concat(all_data, ignore_index=True)
 12%|█▏        | 30/256 [35:22<3:25:20, 54.51s/it]/tmp/ipykernel_8174/1387564697.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_data = pd.concat(all_data, ignore_index=True)
 12%|█▏        | 31/256 [36:10<3:17:08, 52.57s/it]/tmp/ipykernel_8174/1387564697.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_data = pd.concat(all_data, ignore_index=True)
 12%|█▎        | 32/256 [37:00<3:13:29, 51.83s/it]/tmp/ipykernel_8174/1387564697.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_data = pd.concat(all_data, ignore_index=True)
 13%|█▎        | 33/256 [37:49<3:09:02, 50.86s/it]/tmp/ipykernel_8174/1387564697.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_data = pd.concat(all_data, ignore_index=True)
 13%|█▎        | 34/256 [38:38<3:06:19, 50.36s/it]/tmp/ipykernel_8174/1387564697.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_data = pd.concat(all_data, ignore_index=True)
 14%|█▎        | 35/256 [39:31<3:08:12, 51.10s/it]/tmp/ipykernel_8174/1387564697.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_data = pd.concat(all_data, ignore_index=True)
 14%|█▍        | 36/256 [40:17<3:01:45, 49.57s/it]/tmp/ipykernel_8174/1387564697.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_data = pd.concat(all_data, ignore_index=True)
 14%|█▍        | 37/256 [41:10<3:04:17, 50.49s/it]/tmp/ipykernel_8174/1387564697.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_data = pd.concat(all_data, ignore_index=True)
 15%|█▍        | 38/256 [41:58<3:01:46, 50.03s/it]/tmp/ipykernel_8174/1387564697.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_data = pd.concat(all_data, ignore_index=True)
 15%|█▌        | 39/256 [42:44<2:55:56, 48.65s/it]/tmp/ipykernel_8174/1387564697.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_data = pd.concat(all_data, ignore_index=True)
 16%|█▌        | 40/256 [43:30<2:52:13, 47.84s/it]/tmp/ipykernel_8174/1387564697.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_data = pd.concat(all_data, ignore_index=True)
 16%|█▌        | 41/256 [44:16<2:49:24, 47.28s/it]/tmp/ipykernel_8174/1387564697.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_data = pd.concat(all_data, ignore_index=True)
 16%|█▋        | 42/256 [46:50<4:42:44, 79.27s/it]/tmp/ipykernel_8174/1387564697.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_data = pd.concat(all_data, ignore_index=True)
 17%|█▋        | 43/256 [47:39<4:09:20, 70.23s/it]/tmp/ipykernel_8174/1387564697.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_data = pd.concat(all_data, ignore_index=True)
 17%|█▋        | 44/256 [48:27<3:45:05, 63.71s/it]/tmp/ipykernel_8174/1387564697.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_data = pd.concat(all_data, ignore_index=True)
 18%|█▊        | 45/256 [49:13<3:25:09, 58.34s/it]/tmp/ipykernel_8174/1387564697.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_data = pd.concat(all_data, ignore_index=True)
 18%|█▊        | 46/256 [50:03<3:15:17, 55.80s/it]/tmp/ipykernel_8174/1387564697.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_data = pd.concat(all_data, ignore_index=True)

### Query water chemistry using water location codes (only for the missing Vassdragsområder)

In [25]:
data = {
    "FromRegDate": "1900-01-01",
    "ParameterIDFilter": pars,
    "WaterLocationCodeFilter": wc_codes,
}
wc_missing_vass_df = nivapy.da.post_data_to_vannmiljo("GetRegistrations", data=data)
wc_missing_vass_df.to_csv(f'../data/raw_data/water_chemistry/missing_vass_data_export-{export_date}.csv')
wc_missing_vass_df.head()

,WaterRegistrationID,WaterLocationID,WaterLocationCode,Name,Name_Alternative,SourceID,ActivityID,ActivityName,Employer,Contractor,...,VannomradeID,Vannomrade,VannregionID,Vannregion,WaterType,WaterBodyID,WaterBody,CoordX,CoordY,FilteredSample
0,73908366,14880,015-14880,Tangentjernet,None,None,DRIK,Overvåking av drikkevann,Kongsberg kommune,None,...,5111-01,Numedalslågen,5111,Vest-Viken,L206,015-6150-L,Tangentjernet,196756.066767,6.628839e+06,False
1,73908367,14880,015-14880,Tangentjernet,None,None,DRIK,Overvåking av drikkevann,Kongsberg kommune,None,...,5111-01,Numedalslågen,5111,Vest-Viken,L206,015-6150-L,Tangentjernet,196756.066767,6.628839e+06,False
2,73908368,14880,015-14880,Tangentjernet,None,None,DRIK,Overvåking av drikkevann,Kongsberg kommune,None,...,5111-01,Numedalslågen,5111,Vest-Viken,L206,015-6150-L,Tangentjernet,196756.066767,6.628839e+06,False
3,73908369,14880,015-14880,Tangentjernet,None,None,DRIK,Overvåking av drikkevann,Kongsberg kommune,None,...,5111-01,Numedalslågen,5111,Vest-Viken,L206,015-6150-L,Tangentjernet,196756.066767,6.628839e+06,False
4,73908370,14880,015-14880,Tangentjernet,None,None,DRIK,Overvåking av drikkevann,Kongsberg kommune,None,...,5111-01,Numedalslågen,5111,Vest-Viken,L206,015-6150-L,Tangentjernet,196756.066767,6.628839e+06,False